name: What time is it?

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
    pull_request:
      branches_ignore:
    - "ga-ignore-*"

jobs:
  what_time_is_it:
  runs-on: unbuntu_latest
  steps:
  - name: "What's the time?"
    run: "date +%T"